
export const CHATS_ARTEFACTS_FETCHED = 'chats.CHATS_ARTEFACTS_FETCHED';
export const CHATS_ARTEFACTS_FETCHED_SUCCESS =
	'chats.CHATS_ARTEFACTS_FETCHED_SUCCESS';
export const CHATS_ARTEFACTS_FETCHED_FAILURE =
	'chats.CHATS_ARTEFACTS_FETCHED_FAILURE';

export const CHATS_FETCHED = 'chats.CHATS_FETCHED';
export const CHATS_FETCHED_SUCCESS = 'chats.CHATS_FETCHED_SUCCESS';
export const CHATS_FETCHED_FAILURE = 'chats.CHATS_FETCHED_FAILURE';

export const CHATS_THREAD_OPENED = 'chats.CHATS_THREAD_OPENED';

export const CHATS_THREAD_NEW_MESSAGE = 'chats.CHATS_THREAD_NEW_MESSAGE';
export const CHATS_THREAD_REPLY_FETCHED = 'chats.CHATS_THREAD_REPLY_FETCHED';
export const CHATS_THREAD_REPLY_FETCHED_SUCCESS =
	'chats.CHATS_THREAD_REPLY_FETCHED_SUCCESS';
export const CHATS_THREAD_REPLY_FETCHED_FAILURE =
	'chats.CHATS_THREAD_REPLY_FETCHED_FAILURE';

