/** Action Types */

export const CHATS_FETCHED = 'chats.CHATS_FETCHED';
export const CHATS_FETCHED_SUCCESS = 'chats.CHATS_FETCHED_SUCCESS';
export const CHATS_FETCHED_FAILURE = 'chats.CHATS_FETCHED_FAILURE';

export const CHATS_THREAD_FETCHED = 'chats.CHATS_THREAD_FETCHED';
export const CHATS_THREAD_FETCHED_SUCCESS =
	'chats.CHATS_THREAD_FETCHED_SUCCESS';
export const CHATS_THREAD_FETCHED_FAILURE =
	'chats.CHATS_THREAD_FETCHED_FAILURE';
export const CHATS_THREAD_NEW_MESSAGE = 'chats.CHATS_THREAD_NEW_MESSAGE';
export const CHATS_THREAD_REPLY_FETCHED = 'chats.CHATS_THREAD_REPLY_FETCHED';
export const CHATS_THREAD_REPLY_FETCHED_SUCCESS =
	'chats.CHATS_THREAD_REPLY_FETCHED_SUCCESS';
export const CHATS_THREAD_REPLY_FETCHED_FAILURE =
	'chats.CHATS_THREAD_REPLY_FETCHED_FAILURE';

export const CHATS_NEW_CONVERSATION = 'chats.CHATS_NEW_CONVERSATION';
export const CHATS_NEW_CONVERSATION_SUCCESS =
	'chats.CHATS_NEW_CONVERSATION_SUCCESS';
export const CHATS_NEW_CONVERSATION_FAILURE =
	'chats.CHATS_NEW_CONVERSATION_FAILURE';
