
export const RECOGNISE_CLASSIFY_IMAGE_REQUESTED =
	'recognise.RECOGNISE_CLASSIFY_IMAGE_REQUESTED';
export const RECOGNISE_CLASSIFY_IMAGE_SUCCESS =
	'recognise.RECOGNISE_CLASSIFY_IMAGE_SUCCESS';
export const RECOGNISE_CLASSIFY_IMAGE_FAILURE =
	'recognise.RECOGNISE_CLASSIFY_IMAGE_FAILURE';
